---
- hosts: all
  tasks:
    - name: Ensure standard dirs exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/vc
        - ~/.config/kak
        - ~/.config/skhd
        - ~/.config/yabai
        - ~/.local/bin
      tags: symlink

    - name: Ensure ssh dir exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: "0700"
      tags: symlink

    - name: Clone dotfiles
      git: repo=git@github.com:schickm/dotfiles.git dest=~/vc/dotfiles force=no update=no

    - name: Symlink files
      file: path={{ item.path }} src=~/vc/dotfiles/{{ item.src }} state=link
      tags: symlink
      with_items:
        - src: fish/functions
          path: ~/.config/fish/functions
        - src: editorconfig
          path: ~/.editorconfig
        - src: kakrc
          path: ~/.config/kak/kakrc
        - src: skhdrc
          path: ~/.config/skhd/skhdrc
        - src: yabairc
          path: ~/.config/yabai/yabairc
        - src: tigrc
          path: ~/.tigrc
        - src: ssh/config
          path: ~/.ssh/config
